<img src='./figures/logo-ecole-polytechnique-ve.jpg' style='position:absolute; top:0; right:0;' width='100px' height='' alt='' />

<center>**Bachelor of Ecole Polytechnique**</center>
<center>Computational Mathematics, year 2, semester 1</center>
<center>Lecturer: Lucas Gerin <a href="mailto:lucas.gerin@polytechnique.edu">(send mail)</a></center>

# Combinatorics and Probability 1: Graphs and their Matrices


## Table of contents

- [Counting paths in graphs](#Paths)
- [Absorption probabilities](#Escape)

In [18]:
# execute this part to modify the css style
from IPython.core.display import HTML
def css_styling():
    styles = open("./style/custom2.css").read()
    return HTML(styles)
css_styling()

In [2]:
## loading python libraries

# necessary to display plots inline:
%matplotlib inline   

# load the libraries
import matplotlib.pyplot as plt # 2D plotting library
import numpy as np              # package for scientific computing  

from math import *              # package for mathematics (pi, arctan, sqrt, factorial ...)
import sympy as sympy             # package for symbolic computation
from sympy import *

<div markdown=1 class="Rmk"> Here is the Latex code of a matrix that you can copy/paste throughout the notebook:
$$
M=
\begin{matrix}
v_1 \\ v_2 \\ v_3 
\end{matrix}
\begin{pmatrix}
1 & 1 & 0\\
0 & 0 & 1\\
0 & 1 & 0\\
\end{pmatrix}.
$$


<a id="Paths"></a>
## Counting paths in graphs

### Exercise 1. A first example
Let $G$ be the following graph:
<img src="figures/GrapheBasique.jpg" style="width: 200px;"/>


<div markdown=1 class="DoIt"> Use the adjacency matrix of $G$ to compute the number of paths of length $20$ from $a$ to $b$ in $G$.

In [7]:
G = np.matrix([[0,1,0,0],
              [1,0,1,1],
              [1,0,0,0],
              [1,0,0,0]])

n = 20
print(G**20)

[[1713 1138  737  737]
 [2612 1713 1138 1138]
 [1138  737  488  488]
 [1138  737  488  488]]


<div markdown=1 class="Answers">


### Exercise 2. Enumeration of words

<div markdown=1 class="DoIt"> We say that a word $w$ with letters $a,b$ is $b$-<i>short</i> if there are never $4$ consecutive $b$'s in $w$. For instance,
$$
w_1=aa\color{green}{b}aaaaaa\color{green}{bbb}aaa\color{green}{b}aa
$$
is $b$-short while
$$
w_2=aa\color{green}{b}aa\color{green}{bb}a\color{red}{bbbbbb}aa\color{green}{bb}a
$$
is not. Let $S_n$ be the number of $b$-short words of length $n$ (the length of a word is the number of letters).

1). Write a script which computes $S_1,S_2,\dots,S_{20}$ using a graph and its adjacency matrix. You can consider the following graph:
<img src="figures/Graphe_aabbbaab.jpg" style="width: 200px;"/>


<div markdown=1 class="Answers"> 
1).


In [13]:
# Your code here

<div markdown=1 class="DoIt"> 
We say that a word $w$ with letters $a,b$ is $b$-<i>odd</i> if all the maximal sequences of consecutive $b$'s in $w$ have odd lengths.<br>
For example
$$
w_1=a\color{green}{bbbbb}aaa\color{green}{b}aaaaa
$$
is $b$-odd while
$$
w_2=aaa\color{green}{bbbbb}aa\color{red}{bbbb}a
$$
is not $b$-odd.<br>
Let $D_n$ be the number of $b$-odd words of length $n$. For example, $D_2=3$:
<br><br>
$$
aa,\quad ab,\quad ba
$$
<br>
and $D_3=6$:
<br>
$$
aaa,\quad aab, \quad aba,\quad baa,\quad bab,\quad bbb.
$$

1). Using a graph and its adjacency matrix, write a script which computes $D_1,D_2,\dots,D_{20}$.

<i>(You must carefully explain which graph you choose, and which are the relevant coefficients for the enumeration of $D_n$.)</i>

<div markdown=1 class="Answers"> 
1). 

In [14]:
# Your code here

<a id="Escape"></a>
## Absorption probabilities

### Exercise 3. Labyrinth.

We consider a random robot in the following labyrinth:

<img src="figures/Labyrinthe.jpg" style="width: 250px;"/>

The robot is initially in room $B$ (time $n=0$). At each time step, it chooses uniformly at random$^1$ one of the doors of the room in which it is located, and passes through that door.<br> If the robot hits Exit $1$ (resp. $2$) it stays at Exit $1$ (resp. $2$) forever.<br><br>
($^1$) and independently from what happened before.

<div markdown=1 class="DoIt"> 

Denote by $p(n)\in [0,1]^8$ the vector of the probability distribution of the location of the robot at time $n$.

1) Use a transition matrix $M$ to compute approximate values of $p(5), p(2000)$. 

2) Deduce an approximation of the probability that the robot eventually escapes the labyrinth through Exit $1$.

<div markdown=1 class="Answers"> 
1).

In [15]:
# Your code here

<div markdown=1 class="Answers"> 
2) 

<div markdown=1 class="DoIt">
We still assume that the robot starts at $B$.<br>
Denote by $L_n$  the event "The robot is still in the labyrinth at time $n$" (<i>i.e.</i> it dit not find the exit yet). Use matrix $M$ to plot $n\mapsto \mathbb{P}(L_n)$. (Try $1\leq n\leq 40$.)<br>


In [16]:
# Your code here


<div markdown=1 class="DoIt"> Use the method seen in class and the function `solve` from `SymPy` to compute the <i>exact</i> probability that starting from $B$ the robot escapes the labyrinth through Exit $1$.<br>
Compare with your approximation obtained previously.<br>

<i>Recall that to solve a system with `solve` you must write something like:</i>
```
var('x y')
solve([x-2*y,2*x-1+y,[x,y])
```

<div markdown=1 class="Answers"> (Explain here the strategy)

In [17]:
# Your code here